Github & Heroku config added to ssokenizer.yml
superfly/ssokenizer pull request #1
Opened 2023-07-12 03:54 UTC by chrisbh4

2023-07-13 15:45 UTC, btoews requested changes
I merged `main` into your branch since I'd made some other changes to `ssokenizer.yml`. We're now pulling the port for the `http.address` from the `PORT` environment variable. So, you'll want to set `export PORT=8824` in your `.envrc` for running locally.

2023-07-13 15:45 UTC, btoews commented on etc/ssokenizer.yml
> +      - "repo,user:email"
Let's use the `GITHUB_SCOPES` environment variable here. I've set this appropriately in the production deployment, but you'll need to set it in your `.envrc` for running this locally.

2023-07-13 15:45 UTC, btoews commented on etc/ssokenizer.yml
> +      - "repo,user:email"
Same here. For Heroku, it looks like we currently request `identity,read-protected,write` scopes.

2023-07-13 15:45 UTC, btoews commented on etc/ssokenizer.yml
> +    # amazon, bitbucket, facebook, github, gitlab, google, heroku, microsoft,
Let's remove all the comments from the `github`/`heroku` sections. I put these in the `google` section so people looking at the repo would know what they do, but it's redundant to spell that out for each provider.

2023-07-13 20:23 UTC, chrisbh4 reviewed
I pushed up the new changes for the config to use env variables for scoping and also removed the duplicated comments in the Github and Heroku section. I also set the envrc port=8824.

2023-07-14 21:00 UTC, btoews commented on etc/ssokenizer.yml
> +    client_id: "HEROKU_CLIENT_ID"
This is missing a $, that's why it's not pulling the value from the environment variable

2023-07-15 00:28 UTC, chrisbh4 commented on etc/ssokenizer.yml
> +    client_id: "HEROKU_CLIENT_ID"
That makes sense of course it would be a missing syntax smh but I just pushed up the fix and the client_id is now showing

2023-07-18 20:18 UTC, btoews approved these changes
This looks good. I'll try to get the `HEROKU_*` variables set in production in the next few days and then merge this.

2023-07-19 17:17 UTC, chrisbh4 commented
Sounds good just dm me on slack when the variables are set and I'll merge the PR

2023-07-21 14:07 UTC, btoews commented
The new secrets are set in prod and I've deployed this branch.

2023-07-21 14:07 UTC, merged